version: '3.8'
services:
  server:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      NODE_ENV: development
  redis:
    image: redis:6.0

volumes:
  node_modules:
