version: '3.8'
services:
  server:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
    environment:
      NODE_ENV: development
  redis:
    image: redis:6.0
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass

volumes:
  node_modules:
